# netdata-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdata
  labels:
    app: netdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdata
  template:
    metadata:
      labels:
        app: netdata
    spec:
      containers:
      - name: netdata
        image: netdata/netdata
        ports:
        - containerPort: 19999

